namespace LearningAppWebAPI.Models.Enum;

#pragma warning disable CS1591
public enum PartOfSpeechEnum
{
    Noun, // CAT.. DOG.. SUN...
    Pronoun, // I.. YOU.. HIM... HE...
    Verb, // JUMP... RUN...
    Adjective, // PRETTY... OLD...
    Adverb, // HOW? GENTLY... QUIETLY... 
    Preposition, // BY... WITH..
    Conjunction, // JOINS WORDS AND... OR...
    Interjection, // EXPRESSES EMOTIONS LIKE OH! WOW!
}